use std::error::Error;

pub fn two() -> Result<(), Box<dyn Error>> {
    Ok(())
}